Code sintaxices refactored to php8 version
deniztezcan/laravel-liqpay pull request #1
Opened 2021-12-03 15:20 UTC by kSolovei

2021-12-03 15:36 UTC, deniztezcan commented on src/Support/LiqPay.php
> -namespace DenizTezcan\LiqPay\Support;
???

2021-12-03 15:37 UTC, deniztezcan requested changes
See comment

2021-12-03 15:38 UTC, kSolovei commented on src/Support/LiqPay.php
> -namespace DenizTezcan\LiqPay\Support;
See. Will change

2021-12-03 15:38 UTC, kSolovei commented on src/Support/LiqPay.php
> -namespace DenizTezcan\LiqPay\Support;
got it

2021-12-05 21:10 UTC, kSolovei commented
I figured out with Guzzle, made post request got status 200, when checked the result of function getStatus() , but I can't get witch data I've send, the data sending body is empty, I figured out the signature. Unfortunately, I did not manage to understand what was going wrong.

2021-12-07 16:18 UTC, deniztezcan approved these changes

2021-12-07 16:18 UTC, merged